config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
  namespace :admins do
    resources :users, only: [:index, :show, :update, :edit, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    get 'search' => 'searches#search'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  get "home/about" => "homes#about"
  get "/admins" => "admins/homes#top"

  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

  resource :relationships, only: [:create, :destroy, :show]
  resources :users do
    get :followings, on: :member
    get :followers, on: :member
  end

  patch "/users/:id/hide" => "users#hide", as: 'users_hide'
  get "/users/:id/withdraw" => "users#withdraw", as: "user_withdraw"
  get "/search" => "searches#search"


  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :notifications, only: [:index]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  # Refileの画像投稿時に404を返さないようにする記述
    mount Refile.app, at: Refile.mount_point, as: :refile_app
  # どこにも当てはまらないPath（例外処理）
    get '*not_found' => 'application#render_404'
   

end

app/views/users.1/_info.html.erb
<div class='info'>
<table>
  <tr>
	  <th>N&nbsp;A&nbsp;M&nbsp;E</th>
	  <th>&nbsp;<%= user.last_name_kana %>&nbsp;<%= user.first_name_kana %></th>
  </tr>
  <tr>
	  <th>I&nbsp;N&nbsp;T&nbsp;R&nbsp;O&nbsp;D&nbsp;U&nbsp;C&nbsp;T&nbsp;I&nbsp;O&nbsp;N</th>
	  <th>&nbsp;<%= user.introduction %></th>
  </tr>
 <tr>
    <th>フォローしている人数 〜Your following〜<br><span style="color: yellow">※チャット可能 〜Chat available〜</span></th>
    <th>&nbsp;<%= link_to followings_user_path(user.id) do %>&nbsp;&nbsp;<%= user.followings.count %>人<% end %></th>
  </tr>
  <tr>
    <th>フォローされている人数 〜Your followers〜</th>
    <th>&nbsp;<%= link_to followers_user_path(user.id) do %>&nbsp;&nbsp;<%=user.followers.count %>人<% end %></th>
  </tr>
  <tr>
    <th>会員状態 〜Current status〜</th>
    <th><% if user.is_deleted == false %>
          <span style="color: green">&nbsp;&nbsp;利用中 〜valid〜</span>
          <% else %>
        　&nbsp;&nbsp;退会 〜invalid〜
          <% end %></span>
    </th>
  </tr>
  <tr>
	  <th>

	  </th>
  </tr>
</table><br>
<% if user == current_user %>
      <%= link_to "プロフィール編集 Edit profile", edit_user_path(user), class: 'btn btn-outline-light rounded-pill' %>
      <%= link_to "退会する Quit", user_withdraw_path, class: "btn btn-outline-danger" %>
      <% if unchecked_notifications.any? %>
        <i class="fa fa-circle" style="color: gold;"></i>
      <% end %>
      <%= link_to "通知 NOTICE", notifications_path, class: 'btn btn-outline-light rounded-pill' %>
      <% end %>
</div>

app/views/users.1/edit.html.erb
 <div class='row'>
   <div class="picture" style="width:100%">
    <div class="mx-auto" style="width:70%">
      <div class="box"><br>
 <div class="field"><span style="font-size:20px; text-center"><h2>ユーザ情報編集 〜 Edit my profile 〜</h2></span></div>
   <% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
  <%= form_with model: @user, local:true do |f| %>

    <div class="field">
    <%= f.label :名前　姓 %>
    <%= f.text_field :last_name, autofocus: true, placeholder: 'last name' %>

    <%= f.label :　名 %>
    <%= f.text_field :first_name, autofocus: true, placeholder: 'first name' %>
  </div>

  <div class="field">
    <%= f.label :ローマ字（半角）姓 %>
    <%= f.text_field :last_name_kana, autofocus: true, placeholder: 'Fill in English' %>

    <%= f.label :名 %>
    <%= f.text_field :first_name_kana, autofocus: true, placeholder: 'Fill in English' %>
  </div>

  <div class="field">
     <%= f.label :紹介文 %><br />
     <%= f.text_area :introduction, autofocus: true, placeholder: 'Introduction', size: "50x5" %>
  </div>

  <div class="field">
      <%= f.label :プロフィール画像 %>
      <%= f.attachment_field :image, autofocus: true %>
  </div>
  <br>
  <div class="actions">
     <%= f.submit "保存", class: 'btn btn-outline-light btn-lg rounded-pill' %>
  </div>
  <% end %>
  <br>

  </div>
  </div>
 </div>
</div>

app/views/users.1/followers.html.erb
<div class='row'>
   <div class="picture" style="width:100%">
    <div class="mx-auto" style="width:70%">
      <div class="box"><br>
       <div class="col-lg-12">
<h3 class="text-center">フォロワー 〜Your follower〜</h3>
<%= paginate @users %><br>
<% @users.each do |user| %>
    <div class="product-box">
<table>
      <tr>
        <th><%= link_to user_path(user) do %><%= attachment_image_tag(user, :image, :fill, 65, 65, fallback: "no_image.jpg") %><% end %></th>
      </tr>
      <tr>
        <th><%= user.last_name_kana %><%= user.first_name_kana %></th>
      </tr>
    </table>
</div>
<% end %>
</div>
</div>
  </div>
 </div>
</div>

app/views/users.1/followings.html.erb
<div class='row'>
   <div class="picture" style="width:100%">
    <div class="mx-auto" style="width:70%">
      <div class="box"><br>
       <div class="col-lg-12">
<h3 class="text-center">フォローしているユーザー 〜Your following〜 </h3>
<%= paginate @users %><br>
<% @users.each do |user| %>
<div class="product-box">
<table>
      <tr>
        <th><div class="field"><%= link_to user_path(user) do %><%= attachment_image_tag(user, :image, :fill, 65, 65, fallback: "no_image.jpg") %><% end %></div></th>
      </tr>
      <tr>
        <th><div class="field"><%= user.last_name_kana %><%= user.first_name_kana %></div></th>
      </tr>
      <tr>
         <th><%= link_to 'CHAT', chat_path(@user.id), class: 'btn btn-outline-warning rounded-pill' %></th>
      </tr>
</table>
</div>
<% end %>
</div>
</div>
  </div>
 </div>
</div>

app/views/users.1/show.html.erb
<div class='row'>
    <div class="mx-auto" style="width:80%">
      <div class="postbox"><br>
      <div class="container">
        <div class="profile">
        <%= attachment_image_tag(@user, :image, :fill, 200, 200, fallback: "no_image.jpg") %>
        </div>
        <%= render 'users/info', user: @user %>
        </div>
      <div class="actions">
<% if @user == current_user %>
  <% else %>
 <% if current_user.following?(@user) %>
   <%= form_with model:@relationship, url:relationships_path, method: :delete, local: true do |f| %>
   <%= f.hidden_field :followed_id, value: @user.id %>
   <%= f.submit "フォロー外す", class: 'btn btn-outline-light btn-lg rounded-pill' %>
   <% end %>
   <% else %>
   <%= form_with model:@set_relationship, url:relationships_path, local: true do |f| %>
   <%= f.hidden_field :followed_id, value: @user.id %>
   <%= f.submit "フォローする", class: 'btn btn-outline-light btn-lg rounded-pill' %>
  <% end %>
 <% end %>
 <% end %>
<br></div>
<%= render 'posts/index', posts: @posts%>
</div>
 </div>
</div>

app/views/users.1/withdraw.html.erb
<div class='row'>
   <div class="picture" style="width:100%">
    <div class="mx-auto" style="width:70%">
      <div class="box"><br>
      <div class="field">
<h1>退会確認</h1>
     <p>本当に退会してもよろしいでしょうか？</p>
     <% if user_signed_in? && @user.id == current_user.id %>
      <%= link_to "退会する", users_hide_path(current_user), method: :patch, class: "btn btn-outline-danger" %>
     <% end %>
      <%= link_to "退会しない", user_path(current_user), class: "btn btn-outline-light rounded-pill" %>
      </div><br><br>
    </div>
  </div>
 </div>
</div>