config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
  namespace :admins do
    resources :users, only: [:index, :show, :update, :edit, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    get 'search' => 'searches#search'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  get "home/about" => "homes#about"
  get "/admins" => "admins/homes#top"

  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

  resource :relationships, only: [:create, :destroy, :show]
  resources :users do
    get :followings, on: :member
    get :followers, on: :member
  end

  patch "/users/:id/hide" => "users#hide", as: 'users_hide'
  get "/users/:id/withdraw" => "users#withdraw", as: "user_withdraw"
  get "/search" => "searches#search"


  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :notifications, only: [:index]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  # Refileの画像投稿時に404を返さないようにする記述
    mount Refile.app, at: Refile.mount_point, as: :refile_app
  # どこにも当てはまらないPath（例外処理）
    get '*not_found' => 'application#render_404'
   

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :last_name_kana, format: { with: /\A[a-z0-9]+\z/ }
  # 半角英数字のみバリデーション
  validates :first_name, presence: true
  validates :first_name_kana, format: { with: /\A[a-z0-9]+\z/ }
  # 半角英数字のみバリデーション
  validates :introduction, length: { maximum: 100 }
  validates :email,
            format: { with: /\A[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*\z/ },
            presence: true
  validates :encrypted_password, presence: true

  attachment :image, destroy: false
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :posts, through: :favorites

  # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # @user.yyyで、そのユーザがフォローしている人orフォローされている人の一覧を出します。
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def following?(follower)
    followings.include?(follower)
  end

  def follow(follower)
    unless self == follower
      relationships.find_or_create_by(followed_id: follower.id)
    end
  end

  def unfollow(follower)
    relationship = relationships.find_by(followed_id: follower.id)
    relationship.destroy if relationship
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("last_name_kana LIKE ?", "#{word}").or(User.where("first_name_kana LIKE ?", "#{word}"))
    elsif search == "forward_match"
      @user = User.where("last_name_kana LIKE ?", "#{word}").or(User.where("first_name_kana LIKE ?", "#{word}%"))
    elsif search == "backward_match"
      @user = User.where("last_name_kana LIKE ?", "#{word}").or(User.where("first_name_kana LIKE ?", "%#{word}"))
    elsif search == "partial_match"
      @user = User.where("last_name_kana LIKE ?", "#{word}").or(User.where("first_name_kana LIKE ?", "%#{word}%"))
    else
      @user = User.all
    end
  end

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy
  # 自分が作った通知　visiter_idを参考にactive_notificationsモデルへアクセスする
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  # 自分宛の通知 visited_idを参考にpassive_notificationsモデルへアクセスする

  # フォロー時の通知
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to admins_user_path(@user)
    else
      @user = User.find(params[:id])
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admins_users_path
  end

  def user_params
    params.require(:user).permit(:is_deleted)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user.present?
      @valid_pass = @user.valid_password?(params[:user][:password])
      @valid_user = @user.active_for_authentication?

      if @user && @valid_pass && !@valid_user
        # p "退会済処理"
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path

      else
        flash[:error] = "必須項目を入力してください。"
      end
    end
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(5)
    @relationship = current_user.relationships.find_by(followed_id: @user.id)
    @set_relationship = current_user.relationships.new
  end

  def hide
    @user = User.find(params[:id])
    # is_deletedカラムにフラグを立てる(defaultはfalse)
    @user.update(is_deleted: true)
    # ログアウトさせる
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    NotificationMailer.send_confirm_to_user(@user).deliver
    # 退会した際のユーザーへ通知メール
    redirect_to root_path
  end

  def withdraw
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      @users = User.find(params[:id])
      render :edit
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all.page(params[:page]).per(6)
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all.page(params[:page]).per(6)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :introduction, :image)
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<div class='row'>
 <div class="mx-auto" style="width:70%">
  <%= form_with model: @user, url: admins_user_path, method: :patch, local:true do |f| %>
   <p class="text-center">
    <span style="font-size:35px">
     <%= f.label :会員ステータス %>
    </span><br><br>
     <%= f.radio_button :is_deleted, false %>
     <%= f.label :is_deleted, "有効" %>
     <%= f.radio_button :is_deleted, true %>
     <%= f.label :is_deleted, "退会" %><br><br>
     <!--デフォルトがfalseの会員有効-->
     <%= f.submit "ステータスを保存", class: "btn btn-success"%>
  <% end %>
 </div>
</div>

app/views/admins/users/index.html.erb
<div class='row'>
 <div class="mx-auto" style="width:70%">
  <p class="text-center"><span style="font-size:35px">Word Share User 一覧</span></p>
   <div class="field"><br>
    <%= form_with url: admins_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Post']]) %>
      <!--管理人サイドは実用性を考えてUserとPost2つとも実装-->
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary btn-lg" %>
    <% end %>
    <%= paginate @users %>
  </div><br>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th>会員ID</th>
      <th>会員登録日時</th>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
      <th>フォロー数</th>
      <th>フォロワー数</th>
     </tr>
    </thead>
    <tbody>
     <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
      <td>
        <%= link_to admins_user_path(user) do %><%= user.last_name+user.first_name %>(<%= user.last_name_kana+user.first_name_kana %>)<% end %>
      </td>
      <td><%= user.email %></td>
      <td><% if user.is_deleted == false %>
       <span style="color: green">有効</span>
       <% else %>
       <span style="color: gray">退会済み</span>
          <% end %>
      </td>
      <td><%= user.followings.count %></td>
      <td><%=user.followers.count %></td>
    </tr>
     <% end %>
    </tbody>
   </table>
 </div>
</div>

app/views/admins/users/show.html.erb
<div class='row'>
 <div class="mx-auto" style="width:70%">
  <p class="text-center">
    <span style="font-size:30px;">
      <%= @user.last_name_kana+@user.first_name_kana %>&nbsp;詳細情報
    </span><br>
      <%= link_to "編集する", edit_admins_user_path(@user), class: "btn btn-success" %>
      <%= link_to 'ユーザ情報を削除する', admins_user_path(@user), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_user_#{@user.id}"%>
  </p><br>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th>名前</th>
      <th>ふりがな</th>
      <th>プロフィール画像</th>
      <th>紹介文</th>
      <th>ステータス</th>
      <th>フォロー数</th>
      <th>フォロワー数</th>
     </tr>
    </thead>
    <tbody>
     <tr>
      <td><%= @user.last_name+@user.first_name %></td>
      <td><%= @user.last_name_kana+@user.first_name_kana %></td>
      <td><%= attachment_image_tag(@user, :image, :fill, 100, 100, fallback: "no_image.jpg") %></td>
      <td><%= @user.introduction %></td>
      <td><% if @user.is_deleted == false %>
          <span style="color: green">有効</span>
          <% else %>
          <span style="color: gray">退会済み</span>
          <% end %>
      </td>
      <td><%= @user.followings.count %></td>
      <td><%= @user.followers.count %></td>
     </tr>
    </tbody>
   </table>
  </div>
</div>