config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
  namespace :admins do
    resources :users, only: [:index, :show, :update, :edit, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    get 'search' => 'searches#search'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  get "home/about" => "homes#about"
  get "/admins" => "admins/homes#top"

  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

  resource :relationships, only: [:create, :destroy, :show]
  resources :users do
    get :followings, on: :member
    get :followers, on: :member
  end

  patch "/users/:id/hide" => "users#hide", as: 'users_hide'
  get "/users/:id/withdraw" => "users#withdraw", as: "user_withdraw"
  get "/search" => "searches#search"


  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :notifications, only: [:index]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  # Refileの画像投稿時に404を返さないようにする記述
    mount Refile.app, at: Refile.mount_point, as: :refile_app
  # どこにも当てはまらないPath（例外処理）
    get '*not_found' => 'application#render_404'
   

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 100 }
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @post = Post.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @post = Post.where("name LIKE?", "%#{word}%")
    else
      @post = Post.all
    end
  end

  has_many :notifications, dependent: :destroy

 # 投稿がいいねされた時の通知設定
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: "favorite"
    )
    notification.save if notification.valid?
  end
 

  def create_notification_post_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'post_comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.all.page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admins_posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.all.page(params[:page]).per(5)
    @post = current_user
    @all_ranks = Post.find(Favorite.group(:post_id).order(Arel.sql('count(post_id) desc')).limit(3).pluck(:post_id))
    # post_idの中でいいね多い順を上位３つ取り出します。
    @my_ranks = @all_ranks.select { |post| post.user_id == current_user.id }.take(3)
    # ログインユーザの投稿でいいね多い順を上から３つ取得します。
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      redirect_to posts_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user == current_user
      render :edit
    else
      redirect_to post_path(@post)
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:name, :body, :user_id)
  end
  
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: Post.new, local:true do |f| %>
  <%= f.label :言葉 %>
  <%= f.text_field :name, placeholder: "Let's Share Words!", class: 'form-control post_name' %>
  <%= f.label :意味・説明 %>
   <div><span id=countUp>0</span>文字</div>
  <%= f.text_area :body, placeholder: "100文字以内です。Within 100characters", size: "35x5", class: 'form-control post_body' %><br>
  <%= f.submit "Share!", class: 'btn btn-outline-light btn-lg rounded-pill' %>
<% end %><br>

app/views/posts/_index.html.erb
 <% posts.each do |post| %>
  <div class="product-box">
   <table>
    <tr>
     <th>
       <span style="font-size:30px; text-center">
         <%= link_to post_path(post) do %>
          <%= post.name %>
         <% end %>
       </span>
     </th>
    </tr>
    <tr>
     <th>
       <span style="font-size:15px">
         コメント数&nbsp;<%= post.post_comments.count %>
       </span>
     </th>
    </tr>
    <tr>
     <th>
       <span style="font-size:15px">
         いいね数&nbsp;<%= post.favorites.count %>
       </span>
     </th>
    </tr>
   </table>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class='row'>
  <div class="picture" style="width:100%">
    <div class="mx-auto" style="width:70%">
      <div class="box"><br>
        <div class="field">
          <span style="font-size:20px; text-center">
            投稿単語　編集 〜Editing your word〜
          </span>
        </div>
        <div class="field">
        <% if @post.errors.any? %>
         <%= @post.errors.count %>件のエラーが発生しました<br>
          <% @post.errors.full_messages.each do |message| %>
          <%= message %><br>
          <% end %>
        <% end %>
        </div>
    	  <%= form_with model:@post, local: true do |f| %>
         <div class="field">
          <%= f.label :単語 %><br>
          <%= f.text_field :name, autofocus: true, size: "30" %><br>
         </div>
         <div class="field"><br>
          <%= f.label :説明 %><br>
          <%= f.text_area :body, autofocus: true, size: "50x5" %><br><br>
          <%= f.submit 'Update!', class: 'btn btn-outline-light btn-lg rounded-pill' %>
         </div>
         <div class="field"><br>
  	      <h4>
  	        <%= link_to '投稿した単語に戻る 〜word details〜', post_path(@post), class: "book_#{@post.id}" %> |
  	        <%= link_to '投稿一覧へ 〜all words〜', posts_path, class: "back" %>
  	      </h4>
  	     </div>
  		  <% end %>
  		  <br><br>
  		</div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<script src="//cdn.jsdelivr.net/gh/mntn-dev/t.js/t.min.js"></script>
  <div class='row'>
    <div class="mx-auto" style="width:80%">
      <div class="postbox"><br>
        <div class="field">
          <p id="hoge">
            <span style="font-size:25px;">
              言葉をシェアして繋がりましょう！<br>
              〜Let's word share and make your community!〜
            </span>
          </p>
          <%= javascript_tag do %>
            $("#hoge").t()
          <% end %>
        </div>
          <div class="container-post">
            <div class="container-text">
              <p>
                <span style="font-size:25px;">
                  総合ランキング
                </span>
              </p>
              <% @all_ranks.each.with_index(1) do |post, i| %>
              <p>
                No.<%= i %>&nbsp;<%= link_to post_path(post) do %><%= post.name %><% end %>
              </p>
              <p>
                いいね数&nbsp;<%= post.favorites.count %>
              </p>
              <% end %>
            </div>
            <div class="container-text">
              <%= render 'form', post: @post %>
            </div>
            <div class="container-text">
              <p>
                <span style="font-size:25px;">
                  マイランキング
                </span>
              </p>
              <% @my_ranks.each.with_index(1) do |post, i| %>
              <p>
                No.<%= i %>&nbsp;<%= link_to post_path(post) do %>
                <%= post.name %>
                <% end %>
              </p>
              <p>
                いいね数&nbsp;<%= post.favorites.count %>
              </p>
              <% end %>
            </div>
          </div>
            <div class="field">
              <%= form_with url: search_path, local: true, method: :get do |f| %>
              <%= f.text_field :word %>
              <%= f.select :range, options_for_select( ['Word'] ) %>
              <!--ユーザselectはあえて削除-->
              <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
              <%= f.submit "検索", class: "btn btn-primary" %>
              <% end %>
            </div>
            <div class="space">
              <%= render 'index', posts: @posts%><br><br>
            </div>
              <%= paginate @posts %><br>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<h1>検索結果</h1>
  <%= render 'users/info', user: @user %>
    <% if @user == current_user %>
      <% else %>
        <% if current_user.following?(@user) %>
          <%= form_with model:@relationship, url:relationships_path, method: :delete, local: true do |f| %>
          <%= f.hidden_field :followed_id, value: @user.id %>
          <%= f.submit "フォロー外す" %>
        <% end %>
        <% else %>
        <%= form_with model:@set_relationship, url:relationships_path, local: true do |f| %>
        <%= f.hidden_field :followed_id, value: @user.id %>
        <%= f.submit "フォローする" %>
        <% end %>
      <% end %>
    <% end %>
  <%= form_with model: @post, url: search_posts_path, local: true, method: :get do |f| %>
    <%= f.select :keyword, options_for_select([["投稿が新しい順","new"], ["投稿が古い順","old"],  ["いいね済みで多い順","favorites"], ["いいね済みで少ない順","unfavorites"]]) %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
 <%= render 'posts/index', posts: @posts%>

app/views/posts/show.html.erb
<div class='row'>
  <div class="mx-auto" style="width:80%">
    <div class="postbox">
      <div class="field">
        <span style="font-size:25px;"><br>
          いいねやコメントをしてコミュニケーションしましょう！<br>
          〜Push button and leave comments!〜
        </span>
        <p>
         <span style="font-size:25px;">
           単語&nbsp;(word)<br><br>
           <%= @post.name %><br>
           <%= social_share_button_tag(@post.name) %>
         </span>
        </p>
          <% if @post.user_id == current_user.id %>
           <%= link_to '編集 Edit', edit_post_path(@post), class: "btn btn-outline-light rounded-pill" %>&nbsp;
           <%= link_to '削除する Delete', post_path(@post), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_post_#{@post.id}" %>
          <% else %>
           <div id="favorite-btn_<%= @post.id %>">
             <%= render 'favorites/favorite', post: @post %>
           </div>
          <% end %>
      </div>
      <div class="container-post">
        <div class="container-text">
          <p>
           <span style="font-size:25px;">
            意味(explanation)
           </span><br><br>
           <%= @post.body %>
          </p>
        </div>
        <div class="container-text">
          <br><%= link_to user_path(@post.user) do %><%= attachment_image_tag(@post.user, :image, :fill, 80, 80, fallback: "no_image.jpg") %><% end %><br><br>
          Shared by <%= link_to user_path(@post.user), class: 'btn btn-outline-light btn-lg rounded-pill' do %><%= @post.user.last_name_kana %><%= @post.user.first_name_kana %><% end %>
        </div>
      </div>
      <div class="field">
       <span style="font-size:15px; text-center"><br>
        <h4>
         コメント件数：<%= @post.post_comments.count %>
        </h4>
       </span>
      </div>
      <div class="comment">
       <% @post.post_comments.each do |post_comment| %>
        <span style="font-size:15px; text-center">
         <p><br>
          <%= attachment_image_tag(post_comment.user, :image, :fill, 65, 65, fallback: "no_image.jpg") %>
          <%= post_comment.user.last_name_kana %><%= post_comment.user.first_name_kana %>
          <%= post_comment.created_at.strftime('%Y/%m/%d') %><br><br>
          <%= post_comment.comment %>
          </p>
        </span>
        <% if post_comment.user == current_user %>
        <%= link_to "自分のコメントを削除", post_post_comment_path(post_comment.post, post_comment),class: "btn btn-outline-danger btn-sm", remote: true, method: :delete %>
        <% end %>
       <% end %>
      </div>
      <div class="comment-post">
        <%= form_with(model:[@post, @post_comment], remote: true) do |f| %>
          <div>
           <span id=countUp>0</span>文字
          </div>
          <script>
         $(function () {
            $("textarea").keyup(function(){
              var counter = $(this).val().length;
              $("#countUp").text(counter);
              if(counter == 0){
                $("#countUp").text("0");
              }
              if(counter >= 100){
                $("#countUp").css("color","red");
              } else {
                $("#countUp").css("color","white");
              }
            });
          });
          </script>
         <%= f.text_area :comment, rows:'2',placeholder: "コメント100文字以内", size: "30x2" %><br>
         <%= f.submit "送信する", class: 'btn btn-outline-light btn-sm rounded-pill' %>
        <% end %>
     </div>
    </div>
   </div>
  </div>
</div>